apiVersion: authorization.ai-playground.io/v1alpha1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controllers
  name: role-sample
spec:
  isApproved: true
  parentRole:
    type: ClusterRole
    name: clusterrole-sample
  rules:
    - apiGroups:
        - container.ai-playground.io
      resources:
        - containers
      verbs:
        - get
    - apiGroups:
        - container.ai-playground.io
      resources:
        - containers
      verbs:
        - list
    - apiGroups:
        - authorization.ai-playground.io
      resources:
        - groups/approval
      verbs:
        - update
    - apiGroups:
        - container.ai-playground.io
      resources:
        - containers
      verbs:
        - delete