apiVersion: authorization.ai-playground.io/v1alpha1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterrole-sample
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controllers
  name: clusterrole-sample
spec:
  # TODO(user): Add fields here
