apiVersion: dataset.ai-playground.io/v1alpha1
kind: DynamicMount
metadata:
  labels:
    app.kubernetes.io/name: dynamicmount
    app.kubernetes.io/instance: dynamicmount-sample
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controllers
  name: dynamicmount-sample
spec:
  # TODO(user): Add fields here
