apiVersion: image.ai-playground.io/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: image
    app.kubernetes.io/instance: image-sample
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controllers
  name: image-sample
spec:
  imageNameWithTag: "nginx:latest"
  # TODO(user): Add fields here
