apiVersion: playground.ai-playground.io/v1alpha1
kind: Playground
metadata:
  labels:
    app.kubernetes.io/name: playground
    app.kubernetes.io/instance: playground-sample
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controllers
  name: playground-sample
spec:
  # TODO(user): Add fields here
