# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/container.ai-playground.io_containers.yaml
- bases/container.ai-playground.io_containersnapshots.yaml
- bases/dataset.ai-playground.io_datasets.yaml
- bases/dataset.ai-playground.io_dynamicmounts.yaml
- bases/image.ai-playground.io_images.yaml
- bases/nni.ai-playground.io_experiments.yaml
- bases/resource.ai-playground.io_resources.yaml
- bases/playground.ai-playground.io_playgrounds.yaml
- bases/authorization.ai-playground.io_clusterroles.yaml
- bases/authorization.ai-playground.io_roles.yaml
- bases/authorization.ai-playground.io_groups.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_containers.yaml
#- patches/webhook_in_containersnapshots.yaml
#- patches/webhook_in_datasets.yaml
#- patches/webhook_in_dynamicmounts.yaml
#- patches/webhook_in_images.yaml
#- patches/webhook_in_experiments.yaml
#- patches/webhook_in_resources.yaml
#- patches/webhook_in_playgrounds.yaml
#- patches/webhook_in_clusterroles.yaml
#- patches/webhook_in_roles.yaml
#- patches/webhook_in_groups.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_containers.yaml
#- patches/cainjection_in_containersnapshots.yaml
#- patches/cainjection_in_datasets.yaml
#- patches/cainjection_in_dynamicmounts.yaml
#- patches/cainjection_in_images.yaml
#- patches/cainjection_in_experiments.yaml
#- patches/cainjection_in_resources.yaml
#- patches/cainjection_in_playgrounds.yaml
#- patches/cainjection_in_clusterroles.yaml
#- patches/cainjection_in_roles.yaml
#- patches/cainjection_in_groups.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
