/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/apis/container/v1alpha1"
	scheme "github.com/myeong01/ai-playground/pkg/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ContainerSnapshotsGetter has a method to return a ContainerSnapshotInterface.
// A group's client should implement this interface.
type ContainerSnapshotsGetter interface {
	ContainerSnapshots(namespace string) ContainerSnapshotInterface
}

// ContainerSnapshotInterface has methods to work with ContainerSnapshot resources.
type ContainerSnapshotInterface interface {
	Create(ctx context.Context, containerSnapshot *v1alpha1.ContainerSnapshot, opts v1.CreateOptions) (*v1alpha1.ContainerSnapshot, error)
	Update(ctx context.Context, containerSnapshot *v1alpha1.ContainerSnapshot, opts v1.UpdateOptions) (*v1alpha1.ContainerSnapshot, error)
	UpdateStatus(ctx context.Context, containerSnapshot *v1alpha1.ContainerSnapshot, opts v1.UpdateOptions) (*v1alpha1.ContainerSnapshot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ContainerSnapshot, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ContainerSnapshotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContainerSnapshot, err error)
	ContainerSnapshotExpansion
}

// containerSnapshots implements ContainerSnapshotInterface
type containerSnapshots struct {
	client rest.Interface
	ns     string
}

// newContainerSnapshots returns a ContainerSnapshots
func newContainerSnapshots(c *ContainerV1alpha1Client, namespace string) *containerSnapshots {
	return &containerSnapshots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the containerSnapshot, and returns the corresponding containerSnapshot object, and an error if there is any.
func (c *containerSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ContainerSnapshot, err error) {
	result = &v1alpha1.ContainerSnapshot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("containersnapshots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ContainerSnapshots that match those selectors.
func (c *containerSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ContainerSnapshotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ContainerSnapshotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("containersnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested containerSnapshots.
func (c *containerSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("containersnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a containerSnapshot and creates it.  Returns the server's representation of the containerSnapshot, and an error, if there is any.
func (c *containerSnapshots) Create(ctx context.Context, containerSnapshot *v1alpha1.ContainerSnapshot, opts v1.CreateOptions) (result *v1alpha1.ContainerSnapshot, err error) {
	result = &v1alpha1.ContainerSnapshot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("containersnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(containerSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a containerSnapshot and updates it. Returns the server's representation of the containerSnapshot, and an error, if there is any.
func (c *containerSnapshots) Update(ctx context.Context, containerSnapshot *v1alpha1.ContainerSnapshot, opts v1.UpdateOptions) (result *v1alpha1.ContainerSnapshot, err error) {
	result = &v1alpha1.ContainerSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("containersnapshots").
		Name(containerSnapshot.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(containerSnapshot).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *containerSnapshots) UpdateStatus(ctx context.Context, containerSnapshot *v1alpha1.ContainerSnapshot, opts v1.UpdateOptions) (result *v1alpha1.ContainerSnapshot, err error) {
	result = &v1alpha1.ContainerSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("containersnapshots").
		Name(containerSnapshot.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(containerSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the containerSnapshot and deletes it. Returns an error if one occurs.
func (c *containerSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("containersnapshots").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *containerSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("containersnapshots").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched containerSnapshot.
func (c *containerSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContainerSnapshot, err error) {
	result = &v1alpha1.ContainerSnapshot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("containersnapshots").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
