apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authservice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: authservice
subjects:
  - kind: ServiceAccount
    name: authservice
    namespace: istio-system
