/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset"
	authorizationv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/authorization/v1alpha1"
	fakeauthorizationv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/authorization/v1alpha1/fake"
	containerv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/container/v1alpha1"
	fakecontainerv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/container/v1alpha1/fake"
	datasetv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/dataset/v1alpha1"
	fakedatasetv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/dataset/v1alpha1/fake"
	imagev1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/image/v1alpha1"
	fakeimagev1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/image/v1alpha1/fake"
	nniv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/nni/v1alpha1"
	fakenniv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/nni/v1alpha1/fake"
	playgroundv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/playground/v1alpha1"
	fakeplaygroundv1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/playground/v1alpha1/fake"
	resourcev1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/resource/v1alpha1"
	fakeresourcev1alpha1 "github.com/myeong01/ai-playground/cmd/controllers/clientset/clientset/typed/resource/v1alpha1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// AuthorizationV1alpha1 retrieves the AuthorizationV1alpha1Client
func (c *Clientset) AuthorizationV1alpha1() authorizationv1alpha1.AuthorizationV1alpha1Interface {
	return &fakeauthorizationv1alpha1.FakeAuthorizationV1alpha1{Fake: &c.Fake}
}

// ContainerV1alpha1 retrieves the ContainerV1alpha1Client
func (c *Clientset) ContainerV1alpha1() containerv1alpha1.ContainerV1alpha1Interface {
	return &fakecontainerv1alpha1.FakeContainerV1alpha1{Fake: &c.Fake}
}

// DatasetV1alpha1 retrieves the DatasetV1alpha1Client
func (c *Clientset) DatasetV1alpha1() datasetv1alpha1.DatasetV1alpha1Interface {
	return &fakedatasetv1alpha1.FakeDatasetV1alpha1{Fake: &c.Fake}
}

// ImageV1alpha1 retrieves the ImageV1alpha1Client
func (c *Clientset) ImageV1alpha1() imagev1alpha1.ImageV1alpha1Interface {
	return &fakeimagev1alpha1.FakeImageV1alpha1{Fake: &c.Fake}
}

// NniV1alpha1 retrieves the NniV1alpha1Client
func (c *Clientset) NniV1alpha1() nniv1alpha1.NniV1alpha1Interface {
	return &fakenniv1alpha1.FakeNniV1alpha1{Fake: &c.Fake}
}

// PlaygroundV1alpha1 retrieves the PlaygroundV1alpha1Client
func (c *Clientset) PlaygroundV1alpha1() playgroundv1alpha1.PlaygroundV1alpha1Interface {
	return &fakeplaygroundv1alpha1.FakePlaygroundV1alpha1{Fake: &c.Fake}
}

// ResourceV1alpha1 retrieves the ResourceV1alpha1Client
func (c *Clientset) ResourceV1alpha1() resourcev1alpha1.ResourceV1alpha1Interface {
	return &fakeresourcev1alpha1.FakeResourceV1alpha1{Fake: &c.Fake}
}
