# permissions for end users to view dynamicmounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dynamicmount-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controllers
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
  name: dynamicmount-viewer-role
rules:
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - dynamicmounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - dynamicmounts/status
  verbs:
  - get
