# permissions for end users to edit datasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dataset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controllers
    app.kubernetes.io/part-of: controllers
    app.kubernetes.io/managed-by: kustomize
  name: dataset-editor-role
rules:
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - datasets/status
  verbs:
  - get
