---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - clusterroles/finalizers
  verbs:
  - update
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - clusterroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - groups/finalizers
  verbs:
  - update
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - groups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - authorization.ai-playground.io
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - container.ai-playground.io
  resources:
  - containers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.ai-playground.io
  resources:
  - containers/finalizers
  verbs:
  - update
- apiGroups:
  - container.ai-playground.io
  resources:
  - containers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - container.ai-playground.io
  resources:
  - containersnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.ai-playground.io
  resources:
  - containersnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - container.ai-playground.io
  resources:
  - containersnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - datasets/finalizers
  verbs:
  - update
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - dynamicmounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - dynamicmounts/finalizers
  verbs:
  - update
- apiGroups:
  - dataset.ai-playground.io
  resources:
  - dynamicmounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - image.ai-playground.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.ai-playground.io
  resources:
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - image.ai-playground.io
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - nni.ai-playground.io
  resources:
  - experiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nni.ai-playground.io
  resources:
  - experiments/finalizers
  verbs:
  - update
- apiGroups:
  - nni.ai-playground.io
  resources:
  - experiments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - playground.ai-playground.io
  resources:
  - playgrounds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - playground.ai-playground.io
  resources:
  - playgrounds/finalizers
  verbs:
  - update
- apiGroups:
  - playground.ai-playground.io
  resources:
  - playgrounds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.ai-playground.io
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.ai-playground.io
  resources:
  - resources/finalizers
  verbs:
  - update
- apiGroups:
  - resource.ai-playground.io
  resources:
  - resources/status
  verbs:
  - get
  - patch
  - update
